### ISSUE TITLE
Bad gateway

### ISSUE THREAD

**Issue by Jogypilote** [michaeldmoore/CSVServer#14]
Hi all,
I try to use the CSVserver on my already running Grafana server 6.2.4 on a Debian Linux server.
I followed the installation instructions and try now to create the data source. There I get the message 'HTTP error bad gateway'
with the option 'Access: server' when I try to save. With the option 'browser' there is no reaction but I don't get access to any csv file. I have access to Grafana from a remote PC.
Is there any idea where is the problem?
Any help is apprechiated
Joerg

**Comment by michaeldmoore** [comment]
I assume you're running CSVServer on the same computer as grafana - right?
Then I'd use the access server setting with a url like http://localhost:4000
- or whatever.  The http is important.

Take a look at the versions of everything.  Grafana 6.2 should be ok,
though that is pretty old.  There are some problems with SimpleJSON and
simpodJSON and Grafana 7.x (These might have been cured by now).  Stil,
I've been very happy with Grafana 6.5.o

Another thing to look at is the version of node you are running. The latest
LTS version is 12.x.x which works really well.  The bleeding edge version
14.x.x has problems with Grafana, so avoid that.


If you're still getting issues, run CSVServer in a terminal and look at the
output in the terminal when you make a call from Grafana. - You might see
something there that will help figure out the issue.  There are a fair
number of configuration options that you can play with - most often, the
basic out-of-the-box settings are good, so if you've changed any of these -
try putting them back.


Also, open a browser on the server itself, and make the call to
http://localhost:4000  and see what you get in the CSVServer terminal
window - should be something about 'get' and return code 200 or something.

Good luck, and get back to me with some details - such as the terminal
output etc., if you still have problems
Michael Moore

**Comment by Jogypilote** [comment]
ok, I updated Grafana to 6.7.4 and started CSVServer again.
Now it works :-)
Thank you again
Jörg

**Comment by michaeldmoore** [comment]
Good news.

Enjoy

Though - I should repeat the warning, not to run CSVServer in a production
or critical environment.  I created this to help test some grafana panels
etc., and it has turned out to be very useful in that capacity.  I've put a
lot of effort into making it flexible too and I think it works pretty well
- so long as you don't try to process too many records or refresh too many
dashboards rapidly.  You can easily swamp the CPU as very little, if any
optimization has been done in the server code.

Anyway, if you can live within these limitations, enjoy

Michael Moore
